### ISSUE TITLE
There are questions about training my own data set

### ISSUE THREAD

**Issue by h2o2dt** [adeline-cs/GTR#4]
Hello Heyue, your profile picture is prety cute. Wuhan University is my dream university. Readme: Download the training set from Synthesis Training dataset. I want to use my own data set, where should I change the path? By the way, could you give me your wechat? I want to ask some questions about academics. If you would like, please send contact information to 1106981868@qq.com. Best Wishes.

**Comment by ziyi-luo** [comment]
Heyue, you are so beautiful,  please give me your Wechat. pls pls pls. (*╹▽╹*)
